import { StyleSheet, Dimensions } from 'react-native';

const { width, height } = Dimensions.get('window');

const styles = StyleSheet.create({
  modalContainerBackground: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(0, 0, 0, 0.5)",
  },
  modalContent: {
    width: width * 0.95,
    maxHeight: height * 0.8,
    backgroundColor: "#1a1a1a",
    borderRadius: 20,
    padding: 20,
    alignItems: "center",
  },
  scrollViewContent: {
    flexGrow: 1,
    justifyContent: 'center',
  },
  modalTitle: {
    fontSize: 24,
    fontWeight: "bold",
    color: "#f7e8d3",
    marginBottom: 20,
    textAlign: "center",
  },
  modalTaskNameInput: {
    width: "100%",
    fontSize: 16,
    color: "#f7e8d3",
    backgroundColor: "rgba(255, 255, 255, 0.1)",
    borderRadius: 5,
    padding: 10,
    marginBottom: 20,
  },
  priorityLabel: {
    fontSize: 18,
    color: "#f7e8d3",
    marginTop: 10,
    marginBottom: 10,
    alignSelf: "flex-start",
    fontWeight: "bold",
  },
  prioritySelectionContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    width: "100%",
    marginBottom: 20,
  },
  priorityButton: {
    alignItems: "center",
    padding: 10,
    borderRadius: 5,
    borderWidth: 1,
    borderColor: "#f7e8d3",
    flex: 1,
    marginHorizontal: 5,
  },
  priorityButtonSelected: {
    backgroundColor: "#444",
  },
  priorityButtonText: {
    color: "#f7e8d3",
    fontWeight: "bold",
  },
  repetitionLabel: {
    fontSize: 18,
    color: "#f7e8d3",
    marginTop: 10,
    marginBottom: 10,
    alignSelf: "flex-start",
    fontWeight: "bold",
  },
  repetitionButtonsContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    width: "100%",
    marginBottom: 20,
  },
  repetitionButton: {
    alignItems: "center",
    padding: 10,
    borderRadius: 5,
    borderWidth: 1,
    borderColor: "#f7e8d3",
    flex: 1,
    marginHorizontal: 5,
  },
  repetitionButtonSelected: {
    backgroundColor: "#444",
  },
  repetitionButtonText: {
    color: "#f7e8d3",
    fontSize: 14,
  },
  dateLabel: {
    fontSize: 18,
    color: "#f7e8d3",
    marginTop: 10,
    marginBottom: 10,
    alignSelf: "flex-start",
    fontWeight: "bold"
  },
  dateSelectionContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 20,
    width: "100%",
  },
  dateButton: {
    flex: 1,
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    padding: 10,
    borderRadius: 5,
    alignItems: 'center',
  },
  dateButtonText: {
    color: '#f7e8d3',
    fontSize: 16,
  },
  clearDateButton: {
    marginLeft: 10,
    padding: 5,
  },
  modalActionButtons: {
    flexDirection: "row",
    justifyContent: "space-between",
    width: "100%",
    marginTop: 20,
  },
  cancelButton: {
    padding: 15,
    borderRadius: 5,
    backgroundColor: "#FF6347",
    flex: 1,
    marginRight: 10,
    alignItems: "center",
  },
  cancelButtonText: {
    color: "#FFF",
    fontSize: 16,
    fontWeight: "bold",
  },
  addTaskButton: {
    padding: 15,
    borderRadius: 5,
    backgroundColor: "#f7e8d3",
    flex: 1,
    marginLeft: 10,
    alignItems: "center",
  },
  buttonText: {
    color: "#1a1a1a",
    fontSize: 16,
    fontWeight: "bold",
  },
  subtasksLabel: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#f7e8d3',
    marginTop: 20,
    marginBottom: 10,
  },
  subtaskContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 10,
  },
  subtaskInput: {
    flex: 1,
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    borderRadius: 5,
    padding: 10,
    color: '#f7e8d3',
    marginRight: 10,
  },
  deleteSubtaskButton: {
    padding: 5,
  },
  addSubtaskButton: {
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    padding: 10,
    borderRadius: 5,
    alignItems: 'center',
    marginTop: 10,
    marginBottom: 20,
  },
  addSubtaskButtonText: {
    color: '#f7e8d3',
    fontWeight: 'bold',
  },
  modalContainerBackground: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(247, 232, 211, 1)"
  },
  modalContent: {
    width: SCREEN_WIDTH * 0.95,
    maxHeight: SCREEN_WIDTH * 1.3,
    backgroundColor: "#1a1a1a",
    borderRadius: 20,
    padding: 20,
    alignItems: "center",
  },
  scrollViewContent: {
    flexGrow: 1,
    justifyContent: 'center',
  },
  modalTitle: {
    fontSize: SCREEN_WIDTH * 0.06,
    fontWeight: "bold",
    color: "#f7e8d3",
    marginBottom: 20,
    textAlign: "center",
  },
  modalTaskNameInput: {
    width: "100%",
    fontSize: SCREEN_WIDTH * 0.04,
    color: "#f7e8d3",
    backgroundColor: "rgba(255, 255, 255, 0.1)",
    borderRadius: 5,
    padding: 10,
    marginBottom: 20,
  },
  priorityLabel: {
    fontSize: SCREEN_WIDTH * 0.045,
    color: "#f7e8d3",
    marginTop: 10,
    marginBottom: 10,
    alignSelf: "flex-start",
    fontWeight: "bold",
  },
  prioritySelectionContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    width: "100%",
    marginBottom: 20,
  },
  priorityButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: "center",
    justifyContent: "center",
    padding: SCREEN_WIDTH * 0.02,
    borderRadius: 5,
    borderWidth: 1,
    borderColor: "#f7e8d3",
    marginHorizontal: SCREEN_WIDTH * 0.005,
  },
  priorityButtonSelected: {
    backgroundColor: "#444",
  },
  priorityButtonText: {
    color: "#f7e8d3",
    fontWeight: "bold",
    fontSize: SCREEN_WIDTH * 0.03,
    marginLeft: SCREEN_WIDTH * 0.01,
  },
  repetitionLabel: {
    fontSize: SCREEN_WIDTH * 0.045,
    color: "#f7e8d3",
    marginTop: 10,
    marginBottom: 10,
    alignSelf: "flex-start",
    fontWeight: "bold",
  },
  repetitionButtonsContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    width: "100%",
    marginBottom: 20,
  },
  repetitionButton: {
    flex: 1,
    alignItems: "center",
    padding: SCREEN_WIDTH * 0.02,
    borderRadius: 5,
    borderWidth: 1,
    borderColor: "#f7e8d3",
    marginHorizontal: SCREEN_WIDTH * 0.005,
  },
  repetitionButtonSelected: {
    backgroundColor: "#444",
  },
  repetitionButtonText: {
    color: "#f7e8d3",
    fontSize: SCREEN_WIDTH * 0.03,
  },
  dateLabel: {
    fontSize: SCREEN_WIDTH * 0.045,
    color: "#f7e8d3",
    marginTop: 10,
    marginBottom: 10,
    alignSelf: "flex-start",
    fontWeight: "bold"
  },
  dateSelectionContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 20,
    width: "100%",
  },
  dateButton: {
    flex: 1,
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    padding: 10,
    borderRadius: 5,
    alignItems: 'center',
  },
  dateButtonText: {
    color: '#f7e8d3',
    fontSize: SCREEN_WIDTH * 0.04,
  },
  clearDateButton: {
    marginLeft: 10,
    padding: 5,
  },
  
  subtasksLabel: {
    fontSize: SCREEN_WIDTH * 0.045,
    fontWeight: 'bold',
    color: '#f7e8d3',
    marginTop: 20,
    marginBottom: 10,
  },
  subtaskContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 10,
  },
  subtaskInput: {
    flex: 1,
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    borderRadius: 5,
    padding: 10,
    color: '#f7e8d3',
    marginRight: 10,
    fontSize: SCREEN_WIDTH * 0.035,
  },
  deleteSubtaskButton: {
    padding: 5,
  },
  addSubtaskButton: {
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    padding: SCREEN_WIDTH * 0.025,
    borderRadius: 5,
    alignItems: 'center',
    marginTop: 10,
    marginBottom: 20,
  },
  addSubtaskButtonText: {
    color: '#f7e8d3',
    fontWeight: 'bold',
    fontSize: SCREEN_WIDTH * 0.035,
  },
  modalActionButtons: {
    flexDirection: "row",
    justifyContent: "space-between",
    width: "100%",
    marginTop: 20,
  },
  cancelButton: {
    padding: SCREEN_WIDTH * 0.035,
    borderRadius: 5,
    backgroundColor: "#FF6347",
    flex: 1,
    marginRight: 10,
    alignItems: "center",
  },
  cancelButtonText: {
    color: "#FFF",
    fontSize: SCREEN_WIDTH * 0.04,
    fontWeight: "bold",
  },
  addTaskButton: {
    padding: SCREEN_WIDTH * 0.035,
    borderRadius: 5,
    backgroundColor: "#f7e8d3",
    flex: 1,
    marginLeft: 10,
    alignItems: "center",
  },
  buttonText: {
    color: "#1a1a1a",
    fontSize: SCREEN_WIDTH * 0.04,
    fontWeight: "bold",
  },
});

export default styles;